import { dirname, resolve } from 'node:path';
import ts from 'typescript';

import {
  getAnalysisOptions,
  getIncludedEndpoints,
  getTypeContext,
  readNearestPackageName,
  type InternalEndpoint,
} from './analyze';
import type { ApiHttpMethod, HonoApiAnalysis, ResolveTypeImportContext, TypeImportResolution } from './types';

interface RenderContext {
  statusAliases: Map<string, string[]>;
  typeImports: Map<string, { alias: string; moduleSpecifier: string }>;
  importResolutions: Map<string, TypeImportResolution>;
}

interface TypeRenderContext extends RenderContext {
  checker: ts.TypeChecker;
  location: ts.Node;
  analysis: HonoApiAnalysis;
}

interface RegisteredApiInputType {
  moduleSpecifier: string;
  exportName: string;
}

const generatedHeader = '// This file is generated by @xs-rpc/hono. Do not edit.';

const getUnionTypes = (type: ts.Type): readonly ts.Type[] => (type.isUnion() ? type.types : [type]);

const getPropertyType = (
  { checker, location }: Pick<TypeRenderContext, 'checker' | 'location'>,
  type: ts.Type,
  name: string,
): ts.Type => {
  const property = checker.getPropertyOfType(type, name);

  if (!property) {
    throw new Error(`Endpoint type is missing ${name}`);
  }

  return checker.getTypeOfSymbolAtLocation(property, location);
};

const getOptionalPropertyType = (
  context: Pick<TypeRenderContext, 'checker' | 'location'>,
  type: ts.Type,
  name: string,
): ts.Type | undefined => {
  const property = context.checker.getPropertyOfType(type, name);
  return property ? context.checker.getTypeOfSymbolAtLocation(property, context.location) : undefined;
};

const getStringLiteralTypeValue = (checker: ts.TypeChecker, location: ts.Node, type: ts.Type): string | undefined => {
  for (const variant of getUnionTypes(type)) {
    const typeText = checker.typeToString(variant, location, ts.TypeFormatFlags.NoTruncation);

    try {
      const value = JSON.parse(typeText) as unknown;

      if (typeof value === 'string') {
        return value;
      }
    } catch {
      // Optional metadata is represented as a string literal unioned with undefined.
    }
  }

  return undefined;
};

const getRegisteredApiInputType = (context: TypeRenderContext, type: ts.Type): RegisteredApiInputType | undefined => {
  const typeArguments = (type as ts.Type & { aliasTypeArguments?: readonly ts.Type[] }).aliasTypeArguments;
  const marker = context.checker.getPropertyOfType(type, '__apiInputMetadata');
  const markerType = marker ? context.checker.getTypeOfSymbolAtLocation(marker, context.location) : undefined;
  const markerValue = markerType ? getStringLiteralTypeValue(context.checker, context.location, markerType) : undefined;
  const markerSeparator = markerValue?.lastIndexOf('#') ?? -1;
  const markerModuleSpecifier = markerSeparator > 0 ? markerValue?.slice(0, markerSeparator) : undefined;
  const markerExportName = markerSeparator > 0 ? markerValue?.slice(markerSeparator + 1) : undefined;
  const moduleSpecifier = typeArguments?.[0]
    ? getStringLiteralTypeValue(context.checker, context.location, typeArguments[0])
    : markerModuleSpecifier;
  const exportName = typeArguments?.[1]
    ? getStringLiteralTypeValue(context.checker, context.location, typeArguments[1])
    : markerExportName;

  if (!moduleSpecifier || !exportName || !/^[$A-Z_a-z][$\w]*$/u.test(exportName)) {
    return undefined;
  }

  return { moduleSpecifier, exportName };
};

const isBareModuleSpecifier = (moduleSpecifier: string): boolean => {
  return (
    !moduleSpecifier.startsWith('/') && !moduleSpecifier.startsWith('.') && !/^[A-Za-z]:[\\/]/u.test(moduleSpecifier)
  );
};

const getDefaultAlias = (moduleSpecifier: string): string => {
  const parts = moduleSpecifier.split(/[^A-Za-z0-9]+/u).filter(Boolean);
  const alias = parts.map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`).join('');

  if (!/^[$A-Z_a-z][$\w]*$/u.test(alias)) {
    throw new Error(
      `Unable to derive a valid TypeScript namespace alias for ${moduleSpecifier}; provide an alias with resolveTypeImport`,
    );
  }

  return alias;
};

const assertValidCustomAlias = (alias: string, moduleSpecifier: string): void => {
  if (!/^[$A-Z_a-z][$\w]*$/u.test(alias)) {
    throw new Error(
      `Invalid TypeScript namespace alias ${JSON.stringify(alias)} for ${moduleSpecifier}; provide a valid identifier with resolveTypeImport`,
    );
  }
};

const resolveTypeImport = (
  context: TypeRenderContext,
  sourceModuleSpecifier: string,
  kind: ResolveTypeImportContext['kind'],
): TypeImportResolution => {
  const cacheKey = `${kind}\u0000${sourceModuleSpecifier}`;
  const cached = context.importResolutions.get(cacheKey);

  if (cached) {
    return cached;
  }

  const sourceFilePath = context.location.getSourceFile().fileName;
  const custom = getAnalysisOptions(context.analysis).resolveTypeImport?.({
    sourceModuleSpecifier,
    sourceFilePath,
    kind,
  });
  const packageDiscoveryPath = sourceModuleSpecifier.startsWith('.')
    ? resolve(dirname(sourceFilePath), sourceModuleSpecifier)
    : sourceModuleSpecifier;
  const defaultModuleSpecifier = isBareModuleSpecifier(packageDiscoveryPath)
    ? sourceModuleSpecifier
    : readNearestPackageName(packageDiscoveryPath);
  const moduleSpecifier = custom?.moduleSpecifier ?? defaultModuleSpecifier;

  if (!moduleSpecifier) {
    throw new Error(`Unable to resolve a portable package name for ${sourceModuleSpecifier}`);
  }

  if (moduleSpecifier === 'hono' || moduleSpecifier.startsWith('hono/')) {
    throw new Error(`Generated API schemas must not expose Hono types: ${sourceModuleSpecifier}`);
  }

  const resolution = { moduleSpecifier, alias: custom?.alias };
  context.importResolutions.set(cacheKey, resolution);
  return resolution;
};

const getTypeImportAlias = (context: RenderContext, resolution: TypeImportResolution): string => {
  const existing = context.typeImports.get(resolution.moduleSpecifier);

  if (existing) {
    if (resolution.alias && resolution.alias !== existing.alias) {
      throw new Error(
        `Conflicting aliases for ${resolution.moduleSpecifier}: ${existing.alias} and ${resolution.alias}`,
      );
    }

    return existing.alias;
  }

  if (resolution.alias !== undefined) {
    assertValidCustomAlias(resolution.alias, resolution.moduleSpecifier);
  }

  const alias = resolution.alias ?? getDefaultAlias(resolution.moduleSpecifier);
  const collidingImport = [...context.typeImports.values()].find((entry) => entry.alias === alias);

  if (collidingImport) {
    throw new Error(
      `Type import alias ${alias} is used by both ${collidingImport.moduleSpecifier} and ${resolution.moduleSpecifier}`,
    );
  }

  context.typeImports.set(resolution.moduleSpecifier, { alias, moduleSpecifier: resolution.moduleSpecifier });
  return alias;
};

const getPortableTypeText = (context: TypeRenderContext, type: ts.Type): string => {
  const registeredApiInput = getRegisteredApiInputType(context, type);

  if (registeredApiInput) {
    const resolution = resolveTypeImport(context, registeredApiInput.moduleSpecifier, 'registered-api-input');
    return `${getTypeImportAlias(context, resolution)}.${registeredApiInput.exportName}`;
  }

  const typeText = context.checker.typeToString(type, context.location, ts.TypeFormatFlags.NoTruncation);
  const importedModules = [...typeText.matchAll(/import\("([^"]+)"\)/gu)];
  let portableTypeText = typeText;

  for (const importedModule of importedModules) {
    const sourceModuleSpecifier = importedModule[1];

    if (!sourceModuleSpecifier) {
      continue;
    }

    const resolution = resolveTypeImport(context, sourceModuleSpecifier, 'type-reference');
    portableTypeText = portableTypeText.replaceAll(
      `import("${sourceModuleSpecifier}")`,
      getTypeImportAlias(context, resolution),
    );
  }

  return portableTypeText;
};

const getInputTypeText = (context: TypeRenderContext, type: ts.Type): string => {
  const properties = context.checker.getPropertiesOfType(type);

  if (properties.length === 0) {
    return '{}';
  }

  const fields: string[] = [];

  for (const property of properties) {
    const optional = (property.flags & ts.SymbolFlags.Optional) !== 0 ? '?' : '';
    const propertyType = context.checker.getTypeOfSymbolAtLocation(property, context.location);
    const propertyName = /^[$A-Z_a-z][$\w]*$/u.test(property.getName())
      ? property.getName()
      : JSON.stringify(property.getName());
    fields.push(`${propertyName}${optional}: ${getPortableTypeText(context, propertyType)};`);
  }

  return `{ ${fields.join(' ')} }`;
};

const getStatusTypeText = (context: TypeRenderContext, type: ts.Type): string => {
  const alias = type.aliasSymbol?.getName();

  if (alias === 'StatusCode' || alias === 'ContentfulStatusCode') {
    const apiAlias = `Api${alias}`;
    const values = getUnionTypes(type).map((status) =>
      context.checker.typeToString(status, context.location, ts.TypeFormatFlags.NoTruncation),
    );
    const existing = context.statusAliases.get(apiAlias) ?? [];
    context.statusAliases.set(
      apiAlias,
      [...new Set([...existing, ...values])].sort((left, right) => Number(left) - Number(right)),
    );
    return apiAlias;
  }

  return context.checker.typeToString(type, context.location, ts.TypeFormatFlags.NoTruncation);
};

const getEndpointTypeText = (context: TypeRenderContext, endpointType: ts.Type): string => {
  const variants: string[] = [];

  for (const variant of getUnionTypes(endpointType)) {
    const input = getInputTypeText(context, getPropertyType(context, variant, 'input'));
    const output = getPortableTypeText(context, getPropertyType(context, variant, 'output'));
    const outputFormat = getPortableTypeText(context, getPropertyType(context, variant, 'outputFormat'));
    const status = getStatusTypeText(context, getPropertyType(context, variant, 'status'));
    variants.push(`{ input: ${input}; output: ${output}; outputFormat: ${outputFormat}; status: ${status}; }`);
  }

  return variants.join(' | ');
};

const getTypeImportDeclarations = (context: RenderContext): string => {
  return [...context.typeImports.values()]
    .sort((left, right) => left.moduleSpecifier.localeCompare(right.moduleSpecifier))
    .map((entry) => `import type * as ${entry.alias} from ${JSON.stringify(entry.moduleSpecifier)};`)
    .join('\n');
};

const createRenderContext = (analysis: HonoApiAnalysis): TypeRenderContext => ({
  statusAliases: new Map(),
  typeImports: new Map(),
  importResolutions: new Map(),
  analysis,
  ...getTypeContext(analysis),
});

const renderEndpoint = <TResult>(endpoint: InternalEndpoint, render: () => TResult): TResult => {
  try {
    return render();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to render ${endpoint.method} ${endpoint.path}: ${message}`, { cause: error });
  }
};

export const renderApiSchema = (analysis: HonoApiAnalysis): string => {
  const context = createRenderContext(analysis);
  const paths = new Map<string, InternalEndpoint[]>();

  for (const endpoint of getIncludedEndpoints(analysis)) {
    const methods = paths.get(endpoint.path) ?? [];
    methods.push(endpoint);
    paths.set(endpoint.path, methods);
  }

  const schemaEntries: string[] = [];

  for (const [path, endpoints] of paths) {
    const methods: string[] = [];

    for (const endpoint of endpoints) {
      methods.push(
        `    ${JSON.stringify(endpoint.method)}: ${renderEndpoint(endpoint, () => getEndpointTypeText(context, endpoint.type))};`,
      );
    }

    schemaEntries.push(`  ${JSON.stringify(path)}: {\n${methods.join('\n')}\n  };`);
  }

  const statusAliases = [...context.statusAliases.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, statuses]) => `export type ${name} = ${statuses.join(' | ')};`)
    .join('\n');
  const imports = getTypeImportDeclarations(context);
  const prefix = imports ? `${imports}\n\n` : '';
  const statusBlock = statusAliases ? `${statusAliases}\n\n` : '';

  return `${prefix}${generatedHeader}\n\n${statusBlock}export interface ApiSchema {\n${schemaEntries.join('\n')}\n}\n`;
};

const getEndpointInputTypeText = (
  context: TypeRenderContext,
  endpoint: InternalEndpoint,
  inputName: 'query' | 'json',
): string => {
  const typeTexts = new Set<string>();

  for (const variant of getUnionTypes(endpoint.type)) {
    const input = getPropertyType(context, variant, 'input');
    const inputType = getOptionalPropertyType(context, input, inputName);
    typeTexts.add(inputType ? getPortableTypeText(context, inputType) : 'undefined');
  }

  return [...typeTexts].join(' | ');
};

const getEndpointOutputTypeText = (context: TypeRenderContext, endpoint: InternalEndpoint): string => {
  const typeTexts = new Set<string>();

  for (const variant of getUnionTypes(endpoint.type)) {
    const output = getPortableTypeText(context, getPropertyType(context, variant, 'output'));
    typeTexts.add(output === 'null' ? 'undefined' : output);
  }

  return [...typeTexts].join(' | ');
};

const getInputParts = (analysis: HonoApiAnalysis, endpoint: InternalEndpoint): string[] => {
  const context = getTypeContext(analysis);
  const parts = new Set<string>();

  for (const variant of getUnionTypes(endpoint.type)) {
    const input = getPropertyType(context, variant, 'input');

    for (const property of context.checker.getPropertiesOfType(input)) {
      if (property.getName() === 'param' || property.getName() === 'query' || property.getName() === 'json') {
        parts.add(property.getName());
      }
    }
  }

  return ['param', 'query', 'json'].filter((part) => parts.has(part));
};

const getOutputFormats = (analysis: HonoApiAnalysis, endpoint: InternalEndpoint): string[] => {
  const context = getTypeContext(analysis);
  const formats = new Set<string>();

  for (const variant of getUnionTypes(endpoint.type)) {
    const outputFormat = getPropertyType(context, variant, 'outputFormat');

    for (const format of getUnionTypes(outputFormat)) {
      formats.add(
        context.checker.typeToString(format, context.location, ts.TypeFormatFlags.NoTruncation).replaceAll('"', ''),
      );
    }
  }

  return [...formats].sort();
};

export const renderApiManifest = (analysis: HonoApiAnalysis): string => {
  const entries = getIncludedEndpoints(analysis).map((endpoint) => {
    return renderEndpoint(endpoint, () => {
      const key = `${endpoint.method} ${endpoint.path}`;
      return `  { key: ${JSON.stringify(key)}, method: ${JSON.stringify(endpoint.method)}, path: ${JSON.stringify(endpoint.path)}, input: ${JSON.stringify(getInputParts(analysis, endpoint))}, outputFormats: ${JSON.stringify(getOutputFormats(analysis, endpoint))} },`;
    });
  });

  return `${generatedHeader}\n\nexport type ApiManifestInput = 'param' | 'query' | 'json';\nexport type ApiManifestOutputFormat = 'json' | 'text' | 'body';\n\nexport interface ApiManifestEntry {\n  key: string;\n  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';\n  path: string;\n  input: readonly ApiManifestInput[];\n  outputFormats: readonly ApiManifestOutputFormat[];\n}\n\nexport const apiManifest = [\n${entries.join('\n')}\n] as const satisfies readonly ApiManifestEntry[];\n`;
};

interface ContractTreeNode {
  children: Map<string, ContractTreeNode>;
  endpoints: InternalEndpoint[];
}

const createContractTreeNode = (): ContractTreeNode => ({ children: new Map(), endpoints: [] });

const buildContractTree = (analysis: HonoApiAnalysis): ContractTreeNode => {
  const root = createContractTreeNode();

  for (const endpoint of getIncludedEndpoints(analysis)) {
    let node = root;

    for (const segment of endpoint.path.split('/').filter(Boolean)) {
      const child = node.children.get(segment) ?? createContractTreeNode();
      node.children.set(segment, child);
      node = child;
    }

    node.endpoints.push(endpoint);
  }

  return root;
};

const getContractEndpointKey = (method: ApiHttpMethod): string => {
  if (method === 'HEAD' || method === 'OPTIONS') {
    throw new Error(`ts-rest compatibility does not support ${method}; use ApiSchema or a dedicated adapter`);
  }

  return `$${method.toLowerCase()}`;
};

const renderContractEndpoint = (context: TypeRenderContext, endpoint: InternalEndpoint, indent: string): string => {
  const methodKey = getContractEndpointKey(endpoint.method);
  const query = getEndpointInputTypeText(context, endpoint, 'query');
  const output = getEndpointOutputTypeText(context, endpoint);
  const fields = [`method: '${endpoint.method}'`, `path: '${endpoint.path.slice(1)}'`, `query: c.type<${query}>()`];

  if (endpoint.method !== 'GET') {
    fields.push(`body: c.type<${getEndpointInputTypeText(context, endpoint, 'json')}>()`);
  }

  fields.push(`responses: { 200: c.type<${output}>() }`);
  return `${indent}${JSON.stringify(methodKey)}: {\n${fields.map((field) => `${indent}  ${field},`).join('\n')}\n${indent}}`;
};

const renderContractTreeNode = (context: TypeRenderContext, node: ContractTreeNode, indent: string): string => {
  const entries: string[] = [];

  for (const [key, child] of [...node.children.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    entries.push(`${indent}${JSON.stringify(key)}: ${renderContractTreeNode(context, child, `${indent}  `)},`);
  }

  if (node.endpoints.length === 0) {
    return `{\n${entries.join('\n')}\n${indent.slice(2)}}`;
  }

  for (const endpoint of node.endpoints) {
    entries.push(`${renderEndpoint(endpoint, () => renderContractEndpoint(context, endpoint, `${indent}  `))},`);
  }

  return `c.router({\n${entries.join('\n')}\n${indent.slice(2)}})`;
};

export const renderTsRestCompat = (analysis: HonoApiAnalysis): string => {
  const context = createRenderContext(analysis);
  const contractBody = renderContractTreeNode(context, buildContractTree(analysis), '  ');
  const imports = getTypeImportDeclarations(context);
  const prefix = imports ? `${imports}\n` : '';

  return `${prefix}import { initContract } from '@xstools/ts-rest-react-query/ts-rest-core';\n\n${generatedHeader}\n// This is transitional compatibility output; use ApiSchema as the canonical API type source.\n\nconst c = initContract();\n\nexport const contract = ${contractBody};\n`;
};
